"""Добавлено поле text_hash в Document

Revision ID: 759308f835d0
Revises: 
Create Date: 2025-05-12 21:30:02.988516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759308f835d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_text_hash'), ['text_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_text_hash'))
        batch_op.drop_column('text_hash')

    # ### end Alembic commands ###
